#docker run -p 9090:9090 --name patient-survival-prom -v prometheus.yml:/etc/prometheus/prometheus.yml -v prometheus-data:/prometheus prom/prometheus
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: patient-survival
    scheme: http
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout:  5s
    static_configs:
      - targets: ['patient-survival-prediction:8001']